### ISSUE TITLE
Mikroobstarávanie: Ďalšie dáta z ITMS2014+ v ekosystéme

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/harvester.ecosystem#22]
Inštrukcie k funkcionalite sú tu: 

https://docs.google.com/document/d/1T6JQ7rHGjatu4n_J68m-KaBdhyiq1teU0sHqRmjYFxw/edit

- Uchadzaci zaslu cenove ponuky ako verejny komentar na issue na githube. Do pondelka 2.10.2017 12:00 (obeda)
- Maximálna cena 1000 eur.
- Najnizsia ponuka vyhrava. Cenu moze uchadzac znizovat (minimalne o 50 eur).

**Comment by jsuchal** [comment]
FYI: @eronisko @macejmic @mlabaj  (ti co dali ponuky na minule mikroobstaravanie)

**Comment by eronisko** [comment]
1000

**Comment by eronisko** [comment]
Toto je hotovo
