### ISSUE TITLE
Bump gems & ruby

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/harvester.ecosystem#4]
Update [ruby gems](https://gemnasium.com/slovensko-digital/harvester.ecosystem) a ruby na 2.4.1

**Comment by istana** [comment]
I'd like to help with this issue

**Comment by jsuchal** [comment]
@istana go for it! Just ping me with a pull request. 

PS. nechces skusit toto aj za peniaze? https://github.com/slovensko-digital/harvester.ecosystem/issues/6

**Comment by istana** [comment]
@jsuchal ok, done - I can update also to 5.1rc2 if needed

pozriem poziadavky a zvazim to

**Comment by jsuchal** [comment]
Rails zatial nechajme kym bude chvilu stable. A diky!

**Comment by istana** [comment]
okej, tak stable...rad som pomohol

**Comment by jsuchal** [comment]
@istana az by si sa citil na nieco vacsie staci povedat, roboty je dost.
