### ISSUE TITLE
Mikroobstarávanie: Dáta ITMS2014+

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/harvester.ecosystem#6]
Inštrukcie k funkcionalite sú tu: https://docs.google.com/document/d/183nFMy3vnWMkiUfPI2ETkzWPcHd8LLVk4Z2jSmEWtrA/edit#

- Uchadzaci zaslu cenove ponuky ako verejny komentar na issue na githube. **Do pondelka 24.4.2017 12:00 (obeda)**
- Maximálna cena 2000 eur.
- Najnizsia ponuka vyhrava. Cenu moze uchadzac znizovat.

**Comment by macejmic** [comment]
1500 eur.

**Comment by eronisko** [comment]
1400 EUR

**Comment by mlabaj** [comment]
1337 ,–

**Comment by macejmic** [comment]
1300 eur.

**Comment by eronisko** [comment]
1200 EUR

**Comment by macejmic** [comment]
1150 eur.

**Comment by jsuchal** [comment]
Gratulujeme vitazovi @macejmic s ponukou 1150 eur, a @eronisko a @mlabaj za ucast. Tesime sa na dalsiu spolupracu.
